# list of countries the tool is evaluating and sending alerts for:
# - country_id (integer) is the ID of the country
# - emails (list of strings) is the list of addresses to send the notifications to
countries:
  - id: 4
    emails:
      - fabio+country1@tranchitella.eu
      - fabio+country2@tranchitella.eu
  - id: 49
    emails:
      - fabio+country1@tranchitella.eu
      - fabio+country2@tranchitella.eu

global:
  # food security decreases significantly in a country if the percentage of food
  # insecure people in a country increases of >= $threshold compared to the values
  # of $days_ago days ago

  # percentage (5.0 means 5%)
  # NOTE: using 0.1 for debugging purposes, as country #49 triggers the notification
  # while country #1 does not, as of 2020-04-08
  threshold: 0.1

  # days ago (integer)
  days_ago: 30

  # list of email addresses to Cc in all email notifications
  emails:
    - fabio+admin@tranchitella.eu

  # smtp settings; username and password are not mandatory, you can
  # omit them or provide empty values if your smtp server does not require
  # authentication
  smtp:
    sender: fabio+wfp@tranchitella.org
    host: mail.tranchitella.eu
    port: 25
    username: 
    password: 

  # API end-points to get external data
  # - foodsecurity returns the number of food-insecure people in each region
  # - country_regions returns the list of regions for a given country
  api:
    foodsecurity: "https://api.hungermapdata.org/swe-notifications/foodsecurity"
    country_regions: "https://api.hungermapdata.org/swe-notifications/country/%s/regions"